# Generated by Django 4.0.3 on 2022-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_measure_alter_recipe_author_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='abbreviation',
            field=models.CharField(default='default abreviation', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
