# Generated by Django 4.0.3 on 2022-04-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipes.fooditem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipes.measure'),
            preserve_default=False,
        ),
    ]
