# Generated by Django 4.0.3 on 2022-04-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_step_foor_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='foor_items',
            new_name='food_items',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
