# Generated by Django 4.0.3 on 2022-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0003_alter_mealplan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
